support for olimex a64

diff --git a/yunohost/src/config b/yunohost/src/config
--- a/yunohost/src/config
+++ b/yunohost/src/config
@@ -9,6 +9,7 @@ export BASE_WORKSPACE="${DIST_PATH}/workspace"
 export DIST_VERSION=0.1.0
 export BASE_ADD_USER=no
 export BASE_IMAGE_RESIZEROOT=100
+export BASE_SSH_ENABLE="no"
 
 if [[ -z $DIST_NAME ]]; then
   >&2 echo "You must provide a board with DIST_NAME variable"
@@ -18,13 +19,13 @@ fi
 if [[ -z $BASE_DISTRO ]]; then
   case $DIST_NAME in
     *'limeA64'*)
-      export BASE_DISTRO=armbian
+      export BASE_DISTRO=olimex
       export BASE_ARCH=arm64
-      export BASE_ZIP_IMG=$(ls -t ${DIST_PATH}/image/Armbian_*_Lime-a64_*.{zip,7z,xz,img} | head -n 1)
+      export BASE_ZIP_IMG=$(ls -t ${DIST_PATH}/image/{Armbian_*_Lime-a64_*,A64-OLinuXino-*}.{zip,7z,xz,img} 2>/dev/null | head -n 1)
       ;;
     *'lime'*)
       export BASE_DISTRO=armbian
-      export BASE_ZIP_IMG=$(ls -t ${DIST_PATH}/image/Armbian_*_Lime*.{zip,7z,xz,img} | head -n 1)
+      export BASE_ZIP_IMG=$(ls -t ${DIST_PATH}/image/Armbian_*_Lime{,2}_*.{zip,7z,xz,img} 2>/dev/null | head -n 1)
       ;;
     *'odroid'*)
       export BASE_DISTRO=armbian
@@ -34,7 +35,7 @@ if [[ -z $BASE_DISTRO ]]; then
       export BASE_ARCH=arm64
       ;;
     *)
-      >&2 echo "Unable to detect base distribution (armbian or ) for board $DIST_NAME."
+      >&2 echo "Unable to detect base distribution (armbian, olimex or raspbian) for board $DIST_NAME."
       >&2 echo "Please manually provide the base distribution with BASE_DISTRO variable (e.g. armbian or raspbian),"
       >&2 echo "or choose a supported board with DIST_NAME variable (lime, odroid or rpi)." 
       exit 1
@@ -47,19 +48,25 @@ if [[ "${BASE_DISTRO}" == "armbian" ]]; then
   export BASE_ROOT_PARTITION=1
   export BASE_IMAGE_RASPBIAN=no
   export BASE_IMAGE_ENLARGEROOT=1000
-  [[ -n $BASE_ZIP_IMG ]] || export BASE_ZIP_IMG=$(ls -t ${DIST_PATH}/image/Armbian_*.{zip,7z,xz,img} | head -n 1)
-else
+  [[ -n $BASE_ZIP_IMG ]] || export BASE_ZIP_IMG=$(ls -t ${DIST_PATH}/image/Armbian_*.{zip,7z,xz,img} 2>/dev/null | head -n 1)
+elif [[ "${BASE_DISTRO}" == "raspbian" ]]; then
   export BASE_IMAGE_ENLARGEROOT=500
-  [[ -n $BASE_ZIP_IMG ]] || export BASE_ZIP_IMG=$(ls -t ${DIST_PATH}/image/yunohost,*-raspios}-*.{zip,7z,xz,img} | head -n 1)
+  [[ -n $BASE_ZIP_IMG ]] || export BASE_ZIP_IMG=$(ls -t ${DIST_PATH}/image/yunohost,*-raspios}-*.{zip,7z,xz,img} 2>/dev/null | head -n 1)
+elif [[ "${BASE_DISTRO}" == "olimex" ]]; then
+  # The root partiton of the image filesystem, 2 for raspbian, 1 for armbian
+  export BASE_ROOT_PARTITION=1
+  export BASE_IMAGE_RASPBIAN=no
+  export BASE_IMAGE_ENLARGEROOT=1000
+  [[ -n $BASE_ZIP_IMG ]] || export BASE_ZIP_IMG=$(ls -t ${DIST_PATH}/image/*-OLinuXino_*.{zip,7z,xz,img} 2>/dev/null | head -n 1)
 fi
 
 if [[ "${YNH_BUILDER_INSTALLER}" == "internetcube" ]]; then
   export YNH_BUILDER_INSTALL_INTERNETCUBE=yes
-  export BASE_ZIP_IMG=$(ls -t ${DIST_PATH}/image/yunohost_*_${DIST_NAME}-*.{zip,7z,xz,img} | head -n 1)
+  export BASE_ZIP_IMG=$(ls -t ${DIST_PATH}/image/yunohost_*_${DIST_NAME}-*.{zip,7z,xz,img} 2>/dev/null | head -n 1)
   export MODULES="base(internetcube)"
 elif [[ "${YNH_BUILDER_INSTALLER}" == "clic" ]]; then
   export YNH_BUILDER_INSTALL_CLIC=yes
-  export BASE_ZIP_IMG=$(ls -t ${DIST_PATH}/image/yunohost_*_${DIST_NAME}-*.{zip,7z,xz,img} | head -n 1)
+  export BASE_ZIP_IMG=$(ls -t ${DIST_PATH}/image/yunohost_*_${DIST_NAME}-*.{zip,7z,xz,img} 2>/dev/null | head -n 1)
   export MODULES="base(clic)"
 else
   export MODULES="base(yunohost)"
