reuse yunohost for clic and internet cube installers

diff --git a/yunohost/src/config b/yunohost/src/config
--- a/yunohost/src/config
+++ b/yunohost/src/config
@@ -1,34 +1,76 @@
-export BASE_DISTRO=armbian
-export BASE_ADD_USER=no
-export DIST_NAME=lime2
+[[ -n $YNH_BUILDER_INSTALLER ]] || export YNH_BUILDER_INSTALLER=yunohost
+[[ -n $YNH_BUILDER_BRANCH ]] || export YNH_BUILDER_BRANCH=stable
+[[ -n $BASE_RELEASE_COMPRESS ]] || export BASE_RELEASE_COMPRESS=no
+[[ -n $BASE_RELEASE_SHA256 ]] || export BASE_RELEASE_SHA256=no
+# [[ -n $BASE_ARCH ]] || export BASE_ARCH=arm64
+  
+export BASE_WORKSPACE="${DIST_PATH}/workspace"
+
 export DIST_VERSION=0.1.0
+export BASE_ADD_USER=no
+export BASE_IMAGE_RESIZEROOT=100
+
+if [[ -z $DIST_NAME ]]; then
+  >&2 echo "You must provide a board with DIST_NAME variable"
+  exit 1
+fi
+
+if [[ -z $BASE_DISTRO ]]; then
+  case $DIST_NAME in
+    *'limeA64'*)
+      export BASE_DISTRO=armbian
+      export BASE_ARCH=arm64
+      export BASE_ZIP_IMG=$(ls -t ${DIST_PATH}/image/Armbian_*_Lime-a64_*.{zip,7z,xz,img} | head -n 1)
+      ;;
+    *'lime'*)
+      export BASE_DISTRO=armbian
+      export BASE_ZIP_IMG=$(ls -t ${DIST_PATH}/image/Armbian_*_Lime*.{zip,7z,xz,img} | head -n 1)
+      ;;
+    *'odroid'*)
+      export BASE_DISTRO=armbian
+      ;;
+    *'rpi'*)
+      export BASE_DISTRO=raspbian
+      export BASE_ARCH=arm64
+      ;;
+    *)
+      >&2 echo "Unable to detect base distribution (armbian or ) for board $DIST_NAME."
+      >&2 echo "Please manually provide the base distribution with BASE_DISTRO variable (e.g. armbian or raspbian),"
+      >&2 echo "or choose a supported board with DIST_NAME variable (lime, odroid or rpi)." 
+      exit 1
+      ;;
+  esac
+fi
+
 if [[ "${BASE_DISTRO}" == "armbian" ]]; then
   # The root partiton of the image filesystem, 2 for raspbian, 1 for armbian
   export BASE_ROOT_PARTITION=1
   export BASE_IMAGE_RASPBIAN=no
   export BASE_IMAGE_ENLARGEROOT=1000
-  export BASE_ZIP_IMG=$(ls -t ${DIST_PATH}/image/Armbian_*.{zip,7z,xz,img} | head -n 1)
+  [[ -n $BASE_ZIP_IMG ]] || export BASE_ZIP_IMG=$(ls -t ${DIST_PATH}/image/Armbian_*.{zip,7z,xz,img} | head -n 1)
 else
   export BASE_IMAGE_ENLARGEROOT=500
-  export BASE_ZIP_IMG=$(ls -t ${DIST_PATH}/image/*-raspios-*.{zip,7z,xz,img} | head -n 1)
+  [[ -n $BASE_ZIP_IMG ]] || export BASE_ZIP_IMG=$(ls -t ${DIST_PATH}/image/yunohost,*-raspios}-*.{zip,7z,xz,img} | head -n 1)
 fi
 
-export YNH_BUILDER_BRANCH=stable
-export YNH_BUILDER_INSTALL_INTERNETCUBE=yes
+if [[ "${YNH_BUILDER_INSTALLER}" == "internetcube" ]]; then
+  export YNH_BUILDER_INSTALL_INTERNETCUBE=yes
+  export BASE_ZIP_IMG=$(ls -t ${DIST_PATH}/image/yunohost_*_${DIST_NAME}-*.{zip,7z,xz,img} | head -n 1)
+  export MODULES="base(internetcube)"
+elif [[ "${YNH_BUILDER_INSTALLER}" == "clic" ]]; then
+  export YNH_BUILDER_INSTALL_CLIC=yes
+  export BASE_ZIP_IMG=$(ls -t ${DIST_PATH}/image/yunohost_*_${DIST_NAME}-*.{zip,7z,xz,img} | head -n 1)
+  export MODULES="base(clic)"
+else
+  export MODULES="base(yunohost)"
+fi
 
-export MODULES="base(yunohost)"
-
-export BASE_RELEASE_COMPRESS=yes
-export BASE_RELEASE_SHA256=yes
 export BASE_RELEASE_IMG_NAME="${DIST_NAME}-$(date +%Y%m%d)"
 if [[ -f "${BASE_WORKSPACE}/yunohost.tar.gz" ]]; then
-    tar xzf "${BASE_WORKSPACE}/yunohost.tar.gz" -C "${BASE_WORKSPACE}" --strip-components=1
-    YNH_VERSION=$( <${BASE_WORKSPACE}/yunohost_version)
-    BASE_RELEASE_IMG_NAME="${YNH_VERSION}_${BASE_RELEASE_IMG_NAME}"
+  tar xzf "${BASE_WORKSPACE}/yunohost.tar.gz" -C "${BASE_WORKSPACE}" --strip-components=1
 fi
-
-if [[ "${YNH_BUILDER_INSTALL_INTERNETCUBE}" == "yes" ]]; then
-    BASE_RELEASE_IMG_NAME="internetcube_${BASE_RELEASE_IMG_NAME}"
-elif [[ "${YNH_BUILDER_INSTALL_CLIC}" == "yes" ]]; then
-    BASE_RELEASE_IMG_NAME="clic_${BASE_RELEASE_IMG_NAME}" 
+if [[ -f "${BASE_WORKSPACE}/yunohost_version" ]]; then
+  YNH_VERSION=$( <${BASE_WORKSPACE}/yunohost_version)
+  BASE_RELEASE_IMG_NAME="${YNH_VERSION}_${BASE_RELEASE_IMG_NAME}"
 fi
+BASE_RELEASE_IMG_NAME="${YNH_BUILDER_INSTALLER}_${BASE_RELEASE_IMG_NAME}"
